name: Cosmetics
author: CodePunisher
version: 1.0
main: com.codepunisher.cosmetics.CosmMain
depend:
  - HeadDatabase
  - McAimCore
api-version: 1.16

commands:
  cosmetics:
    aliases: [cosmetic, cosm]
    description: cosmetics command